export const standings = {
  season: "2019/20",
  league: "Kreisklasse",
  region: "Kreis Donau/Isar",
  promotedTeams: 1,
  promotedQualifierTeams: 1,
  relegatedQualifierTeams: 2,
  relegatedTeams: 2,
  teams: [
    {
      rank: 1,
      teamname: "TSV Ipferdingen",
      playedGames: 19,
      points: 43,
      wins: 13,
      draws: 4,
      looses: 2,
      goals: "57:17",
      goalsDifference: 40,
    },
    {
      rank: 2,
      teamname: "SV Bohemian Rhapsody",
      playedGames: 18,
      points: 40,
      wins: 12,
      draws: 4,
      looses: 2,
      goals: "44:14",
      goalsDifference: 30,
    },
    {
      rank: 3,
      teamname: "TSV Bandlstadt",
      playedGames: 19,
      points: 42,
      wins: 13,
      draws: 3,
      looses: 3,
      goals: "53:25",
      goalsDifference: 28,
    },
    {
      rank: 4,
      teamname: "SV Ziagan",
      playedGames: 19,
      points: 39,
      wins: 12,
      draws: 3,
      looses: 4,
      goals: "51:23",
      goalsDifference: 28,
    },
    {
      rank: 5,
      teamname: "Vatanspor Leupoldfing",
      playedGames: 19,
      points: 34,
      wins: 9,
      draws: 7,
      looses: 3,
      goals: "48:34",
      goalsDifference: 14,
    },
    {
      rank: 6,
      teamname: "FC Eisenbahner",
      playedGames: 18,
      points: 25,
      wins: 7,
      draws: 4,
      looses: 7,
      goals: "27:27",
      goalsDifference: 0,
    },
    {
      rank: 7,
      teamname: "SV Ilm",
      playedGames: 19,
      points: 26,
      wins: 8,
      draws: 2,
      looses: 9,
      goals: "38:39",
      goalsDifference: -1,
    },
    {
      rank: 8,
      teamname: "FVgg Tschick",
      playedGames: 19,
      points: 22,
      wins: 6,
      draws: 4,
      looses: 9,
      goals: "30:38",
      goalsDifference: -8,
    },
    {
      rank: 9,
      teamname: "SpVgg Oberaber",
      playedGames: 19,
      points: 21,
      wins: 6,
      draws: 3,
      looses: 10,
      goals: "33:52",
      goalsDifference: -19,
    },
    {
      rank: 10,
      teamname: "SC Zwiebel",
      playedGames: 18,
      points: 19,
      wins: 5,
      draws: 4,
      looses: 9,
      goals: "31:44",
      goalsDifference: -13,
    },
    {
      rank: 11,
      teamname: "TSV Bandlhof",
      playedGames: 19,
      points: 20,
      wins: 6,
      draws: 2,
      looses: 11,
      goals: "36:49",
      goalsDifference: -13,
    },
    {
      rank: 12,
      teamname: "SV Wellingen",
      playedGames: 19,
      points: 20,
      wins: 6,
      draws: 2,
      looses: 11,
      goals: "37:48",
      goalsDifference: -11,
    },
    {
      rank: 13,
      teamname: "SpVgg Fliesen",
      playedGames: 19,
      points: 19,
      wins: 6,
      draws: 1,
      looses: 12,
      goals: "34:43",
      goalsDifference: -9,
    },
    {
      rank: 14,
      teamname: "SG Dasammadohaoam",
      playedGames: 18,
      points: 1,
      wins: 0,
      draws: 1,
      looses: 17,
      goals: "14:80",
      goalsDifference: -66,
    },
  ],
};
